# Generated by Django 5.0.6 on 2024-06-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('requester_email', models.EmailField(max_length=255)),
                ('ticker_code', models.CharField(max_length=20)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('buy_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('track_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.trackorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
